<?php

namespace Database\Seeders;

use App\Models\PageSeo;
use Illuminate\Database\Seeder;

class PageSeoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $pages = [
            [
                'page_route' => '/',
                'page_name' => 'Home',
                'is_published' => true,
                'meta_title' => 'Free AI Resume Builder | ATS-Optimized Resume Templates 2026',
                'meta_description' => 'Create ATS-optimized resumes with AI in minutes. 50,000+ professionals hired. Free templates, instant scoring & keyword matching. Start now!',
                'meta_keywords' => 'free resume builder, AI resume builder, ATS resume, ATS-optimized resume, resume templates 2026, professional resume, job application, resume optimizer, ATS checker, career tools',
                'og_title' => 'Free AI Resume Builder | Get Hired 3x Faster - ResumeBP',
                'og_description' => 'Create ATS-optimized resumes with AI. 50,000+ professionals hired. Free templates & instant ATS scoring.',
                'og_type' => 'website',
                'og_url' => 'https://resumebp.com/',
                'og_image' => 'https://resumebp.com/og-home.jpg',
                'og_site_name' => 'ResumeBP',
                'twitter_card' => 'summary_large_image',
                'twitter_title' => 'Free AI Resume Builder | Get Hired 3x Faster',
                'twitter_description' => 'Create ATS-optimized resumes with AI. 50,000+ professionals hired.',
                'twitter_image' => 'https://resumebp.com/og-home.jpg',
                'twitter_site' => '@resumebp',
                'canonical_url' => 'https://resumebp.com/',
                'robots' => 'index, follow',
                'language' => 'en',
                'priority' => 10,
            ],
            [
                'page_route' => '/pricing',
                'page_name' => 'Pricing',
                'is_published' => true,
                'meta_title' => 'Resume Builder Pricing 2026 | Free Plan Available - ResumeBP',
                'meta_description' => 'From $0 to premium plans. Unlimited resumes, AI optimization & ATS checking. 50,000+ professionals hired. Cancel anytime. Start free!',
                'meta_keywords' => 'resume builder pricing, free resume builder, resume subscription plans, AI resume pricing, ATS resume cost, resume templates pricing, professional resume plans, resume builder cost, monthly resume subscription, yearly resume plans',
                'og_title' => 'Affordable Resume Builder Pricing | Plans from $0 - ResumeBP',
                'og_description' => 'Choose from Free, Pro, or Premium plans. Unlimited resumes, AI optimization, ATS checking. 50,000+ professionals hired.',
                'og_type' => 'website',
                'og_url' => 'https://resumebp.com/pricing',
                'og_image' => 'https://resumebp.com/og-pricing.jpg',
                'og_site_name' => 'ResumeBP',
                'twitter_card' => 'summary_large_image',
                'twitter_title' => 'Resume Builder Pricing | Free Plan Available',
                'twitter_description' => 'From $0 to premium plans. Unlimited resumes, AI optimization & ATS checking. Start free today!',
                'twitter_image' => 'https://resumebp.com/og-pricing.jpg',
                'twitter_site' => '@resumebp',
                'canonical_url' => 'https://resumebp.com/pricing',
                'robots' => 'index, follow',
                'language' => 'en',
                'priority' => 9,
            ],
            [
                'page_route' => '/ats-checker',
                'page_name' => 'ATS Checker',
                'is_published' => true,
                'meta_title' => 'Free ATS Resume Checker 2026 | Test Score - ResumeBP',
                'meta_description' => 'Check if your resume passes ATS systems. Free instant analysis. Get your ATS score, keyword match & formatting tips. 90% pass rate. Try now!',
                'meta_keywords' => 'free ATS checker, ATS resume scanner, resume ATS test, applicant tracking system checker, ATS score, resume parser, ATS compatibility test, resume keyword checker, ATS optimization tool, free resume scanner',
                'og_title' => 'Free ATS Resume Checker | Instant Score & Analysis - ResumeBP',
                'og_description' => 'Test your resume against ATS systems for free. Get instant score, keyword analysis & formatting tips. 90% pass rate for optimized resumes.',
                'og_type' => 'website',
                'og_url' => 'https://resumebp.com/ats-checker',
                'og_image' => 'https://resumebp.com/og-ats-checker.jpg',
                'og_site_name' => 'ResumeBP',
                'twitter_card' => 'summary_large_image',
                'twitter_title' => 'Free ATS Resume Checker | Test Your Resume Score',
                'twitter_description' => 'Check if your resume passes ATS systems. Free instant analysis with score, keywords & tips. Try now!',
                'twitter_image' => 'https://resumebp.com/og-ats-checker.jpg',
                'twitter_site' => '@resumebp',
                'canonical_url' => 'https://resumebp.com/ats-checker',
                'robots' => 'index, follow',
                'language' => 'en',
                'priority' => 8,
            ],
            [
                'page_route' => '/contact',
                'page_name' => 'Contact',
                'is_published' => true,
                'meta_title' => 'Contact Us | 24h Response - ResumeBP Support',
                'meta_description' => 'Get help with your resume. Contact our support team for questions about ATS, pricing, or features. 24-hour response time. Email, phone & live chat available.',
                'meta_keywords' => 'contact resume builder, customer support, resume help, ATS support, technical support, resume builder contact, get help, customer service, email support, phone support',
                'og_title' => 'Contact ResumeBP | Fast Support for Your Resume Questions',
                'og_description' => 'Need help with your resume? Our support team responds within 24 hours. Contact us for ATS questions, pricing info, or technical support.',
                'og_type' => 'website',
                'og_url' => 'https://resumebp.com/contact',
                'og_image' => 'https://resumebp.com/og-contact.jpg',
                'og_site_name' => 'ResumeBP',
                'twitter_card' => 'summary_large_image',
                'twitter_title' => 'Contact ResumeBP Support | 24h Response Time',
                'twitter_description' => 'Get help with your resume. Email, phone & live chat support available. 24-hour response time.',
                'twitter_image' => 'https://resumebp.com/og-contact.jpg',
                'twitter_site' => '@resumebp',
                'canonical_url' => 'https://resumebp.com/contact',
                'robots' => 'index, follow',
                'language' => 'en',
                'priority' => 6,
            ],
            [
                'page_route' => '/about',
                'page_name' => 'About',
                'is_published' => true,
                'meta_title' => 'About ResumeBP | AI Resume Builder Mission & Story',
                'meta_description' => 'Learn how ResumeBP helps 50,000+ job seekers create ATS-optimized resumes with AI. Our mission: democratize career success. 90% ATS pass rate.',
                'meta_keywords' => 'about resume builder, company mission, AI resume technology, ATS optimization story, resume builder team, career success platform, job seeker tools, resume AI technology, hiring success',
                'og_title' => 'About ResumeBP | Helping 50,000+ Job Seekers Get Hired',
                'og_description' => 'Learn how ResumeBP uses AI to help job seekers create ATS-optimized resumes. Our mission: democratize career success. 90% ATS pass rate.',
                'og_type' => 'website',
                'og_url' => 'https://resumebp.com/about',
                'og_image' => 'https://resumebp.com/og-about.jpg',
                'og_site_name' => 'ResumeBP',
                'twitter_card' => 'summary_large_image',
                'twitter_title' => 'About ResumeBP | AI Resume Builder Mission',
                'twitter_description' => 'Helping 50,000+ job seekers create ATS-optimized resumes with AI. 90% ATS pass rate.',
                'twitter_image' => 'https://resumebp.com/og-about.jpg',
                'twitter_site' => '@resumebp',
                'canonical_url' => 'https://resumebp.com/about',
                'robots' => 'index, follow',
                'language' => 'en',
                'priority' => 5,
            ],
            [
                'page_route' => '/faq',
                'page_name' => 'FAQ',
                'is_published' => true,
                'meta_title' => 'Frequently Asked Questions - AI Resume Builder',
                'meta_description' => 'Find answers to common questions about our resume builder, pricing, features, and more. Get help with creating your perfect resume.',
                'meta_keywords' => 'FAQ, questions, help, support, resume builder',
                'og_title' => 'Frequently Asked Questions - AI Resume Builder',
                'og_description' => 'Find answers to common questions about our resume builder.',
                'og_type' => 'website',
                'twitter_card' => 'summary',
                'robots' => 'index, follow',
                'language' => 'en',
                'priority' => 6,
            ],
            [
                'page_route' => '/privacy',
                'page_name' => 'Privacy Policy',
                'is_published' => true,
                'meta_title' => 'Privacy Policy - AI Resume Builder',
                'meta_description' => 'Read our privacy policy to understand how we collect, use, and protect your personal information when using our resume builder.',
                'meta_keywords' => 'privacy policy, data protection, GDPR, privacy',
                'og_title' => 'Privacy Policy - AI Resume Builder',
                'og_description' => 'Read our privacy policy to understand how we protect your data.',
                'og_type' => 'website',
                'twitter_card' => 'summary',
                'robots' => 'index, follow',
                'language' => 'en',
                'priority' => 4,
            ],
            [
                'page_route' => '/terms',
                'page_name' => 'Terms of Service',
                'is_published' => true,
                'meta_title' => 'Terms of Service - AI Resume Builder',
                'meta_description' => 'Read our terms of service to understand the rules and guidelines for using our AI-powered resume builder platform.',
                'meta_keywords' => 'terms of service, terms and conditions, legal, agreement',
                'og_title' => 'Terms of Service - AI Resume Builder',
                'og_description' => 'Read our terms of service and usage guidelines.',
                'og_type' => 'website',
                'twitter_card' => 'summary',
                'robots' => 'index, follow',
                'language' => 'en',
                'priority' => 4,
            ],
            [
                'page_route' => '/refund-policy',
                'page_name' => 'Refund & Cancellation Policy',
                'is_published' => true,
                'meta_title' => 'Refund & Cancellation Policy - AI Resume Builder',
                'meta_description' => 'We believe in fairness and transparency. Here is everything you need to know about our billing, refunds, and cancellations.',
                'meta_keywords' => 'refund policy, cancellation policy, money back guarantee, billing',
                'og_title' => 'Refund & Cancellation Policy - AI Resume Builder',
                'og_description' => 'Learn about our 7-day money-back guarantee and cancellation policy.',
                'og_type' => 'website',
                'twitter_card' => 'summary',
                'robots' => 'index, follow',
                'language' => 'en',
                'priority' => 3,
            ],
            [
                'page_route' => '/shipping-policy',
                'page_name' => 'Shipping & Delivery Policy',
                'is_published' => true,
                'meta_title' => 'Shipping & Delivery Policy - AI Resume Builder',
                'meta_description' => 'AI Resume Builder is a fully digital platform. Learn how you access our services instantly with no shipping required.',
                'meta_keywords' => 'shipping policy, delivery policy, digital delivery, instant access',
                'og_title' => 'Shipping & Delivery Policy - AI Resume Builder',
                'og_description' => 'Learn about our instant digital delivery. No shipping fees, no waiting.',
                'og_type' => 'website',
                'twitter_card' => 'summary',
                'robots' => 'index, follow',
                'language' => 'en',
                'priority' => 3,
            ],
        ];

        foreach ($pages as $page) {
            PageSeo::updateOrCreate(
                ['page_route' => $page['page_route']],
                $page
            );
        }

        $this->command->info('Page SEO data seeded successfully!');
    }
}
