<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ResumeTemplateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $templates = [
            // Original Templates
            [
                'template_id' => 'modern',
                'name' => 'Modern Executive',
                'category' => 'Best for Tech & SaaS',
                'description' => 'A sleek, modern template perfect for tech professionals and executives. Features clean lines and a professional layout.',
                'best_for' => 'Software Engineers, Product Managers, Tech Executives',
                'complexity_level' => 'intermediate',
                'sort_order' => 1,
                'is_active' => true,
                'is_premium' => false,
                'plan_tier' => 'free',
                'supported_colors' => ['indigo', 'emerald', 'rose', 'slate', 'amber', 'violet'],
                'features' => ['Clean Layout', 'ATS-Friendly', 'Modern Design', 'Professional'],
            ],
            [
                'template_id' => 'creative',
                'name' => 'Creative Sidebar',
                'category' => 'Design & Marketing',
                'description' => 'Stand out with this creative sidebar design. Perfect for designers and creative professionals.',
                'best_for' => 'Designers, Marketers, Creative Directors',
                'complexity_level' => 'intermediate',
                'sort_order' => 2,
                'is_active' => true,
                'is_premium' => false,
                'plan_tier' => 'free',
                'supported_colors' => ['indigo', 'emerald', 'rose', 'slate', 'amber', 'violet'],
                'features' => ['Sidebar Layout', 'Visual Appeal', 'Creative Design', 'Eye-Catching'],
            ],
            [
                'template_id' => 'academic',
                'name' => 'Academic Elite',
                'category' => 'Formal & Corporate',
                'description' => 'Traditional and formal template ideal for academic positions and corporate roles.',
                'best_for' => 'Professors, Researchers, Corporate Executives',
                'complexity_level' => 'beginner',
                'sort_order' => 3,
                'is_active' => true,
                'is_premium' => false,
                'plan_tier' => 'free',
                'supported_colors' => ['indigo', 'emerald', 'rose', 'slate', 'amber', 'violet'],
                'features' => ['Formal Design', 'Traditional Layout', 'Academic Focus', 'Professional'],
            ],
            [
                'template_id' => 'minimal',
                'name' => 'Minimalist Bold',
                'category' => 'Clean & Functional',
                'description' => 'Less is more. A minimalist design that lets your content shine.',
                'best_for' => 'All Industries, Entry-Level to Senior',
                'complexity_level' => 'beginner',
                'sort_order' => 4,
                'is_active' => true,
                'is_premium' => false,
                'plan_tier' => 'free',
                'supported_colors' => ['indigo', 'emerald', 'rose', 'slate', 'amber', 'violet'],
                'features' => ['Minimalist', 'Clean Lines', 'Easy to Read', 'Versatile'],
            ],

            // Executive & Professional
            [
                'template_id' => 'executive',
                'name' => 'Executive',
                'category' => 'Senior Leadership',
                'description' => 'Designed for C-level executives and senior leadership positions.',
                'best_for' => 'CEOs, VPs, Directors, Senior Managers',
                'complexity_level' => 'advanced',
                'sort_order' => 5,
                'is_active' => true,
                'is_premium' => true,
                'plan_tier' => 'starter',
                'supported_colors' => ['indigo', 'emerald', 'rose', 'slate', 'amber', 'violet'],
                'features' => ['Executive Level', 'Leadership Focus', 'Premium Design', 'Authoritative'],
            ],
            [
                'template_id' => 'professional',
                'name' => 'Professional',
                'category' => 'Corporate & Business',
                'description' => 'A professional template suitable for corporate and business environments.',
                'best_for' => 'Business Analysts, Consultants, Managers',
                'complexity_level' => 'intermediate',
                'sort_order' => 6,
                'is_active' => true,
                'is_premium' => false,
                'plan_tier' => 'starter',
                'supported_colors' => ['indigo', 'emerald', 'rose', 'slate', 'amber', 'violet'],
                'features' => ['Professional', 'Corporate Ready', 'Business Focus', 'Clean'],
            ],
            [
                'template_id' => 'classic',
                'name' => 'Classic',
                'category' => 'Traditional & Formal',
                'description' => 'A timeless classic design that works for any industry.',
                'best_for' => 'All Industries, Traditional Roles',
                'complexity_level' => 'beginner',
                'sort_order' => 7,
                'is_active' => true,
                'is_premium' => false,
                'plan_tier' => 'starter',
                'supported_colors' => ['indigo', 'emerald', 'rose', 'slate', 'amber', 'violet'],
                'features' => ['Classic Design', 'Timeless', 'Universal', 'Traditional'],
            ],

            // Modern & Tech
            [
                'template_id' => 'tech',
                'name' => 'Tech Developer',
                'category' => 'Software & Engineering',
                'description' => 'Optimized for software developers and engineers with a modern tech aesthetic.',
                'best_for' => 'Software Developers, Engineers, DevOps',
                'complexity_level' => 'intermediate',
                'sort_order' => 8,
                'is_active' => true,
                'is_premium' => false,
                'plan_tier' => 'starter',
                'supported_colors' => ['indigo', 'emerald', 'rose', 'slate', 'amber', 'violet'],
                'features' => ['Tech Focus', 'Modern', 'Developer Friendly', 'Skills Highlight'],
            ],
            [
                'template_id' => 'gradient',
                'name' => 'Gradient Modern',
                'category' => 'Creative & Bold',
                'description' => 'Bold gradient design for those who want to make a statement.',
                'best_for' => 'Designers, Creatives, Startups',
                'complexity_level' => 'advanced',
                'sort_order' => 9,
                'is_active' => true,
                'is_premium' => true,
                'plan_tier' => 'starter',
                'supported_colors' => ['indigo', 'emerald', 'rose', 'slate', 'amber', 'violet'],
                'features' => ['Gradient Design', 'Bold', 'Modern', 'Eye-Catching'],
            ],
            [
                'template_id' => 'infographic',
                'name' => 'Infographic',
                'category' => 'Visual & Creative',
                'description' => 'Visual-heavy template with infographic elements to showcase your skills.',
                'best_for' => 'Designers, Data Analysts, Creatives',
                'complexity_level' => 'advanced',
                'sort_order' => 10,
                'is_active' => true,
                'is_premium' => true,
                'plan_tier' => 'starter',
                'supported_colors' => ['indigo', 'emerald', 'rose', 'slate', 'amber', 'violet'],
                'features' => ['Infographic Style', 'Visual', 'Creative', 'Skills Focus'],
            ],

            // Minimalist & Clean
            [
                'template_id' => 'swiss',
                'name' => 'Swiss Style',
                'category' => 'Minimalist & Clean',
                'description' => 'Inspired by Swiss design principles - clean, minimal, and functional.',
                'best_for' => 'Designers, Architects, Minimalists',
                'complexity_level' => 'intermediate',
                'sort_order' => 11,
                'is_active' => true,
                'is_premium' => false,
                'plan_tier' => 'professional',
                'supported_colors' => ['indigo', 'emerald', 'rose', 'slate', 'amber', 'violet'],
                'features' => ['Swiss Design', 'Minimalist', 'Clean', 'Functional'],
            ],
            [
                'template_id' => 'elegant',
                'name' => 'Elegant',
                'category' => 'Refined & Sophisticated',
                'description' => 'Sophisticated and elegant design for refined professionals.',
                'best_for' => 'Executives, Consultants, Luxury Brands',
                'complexity_level' => 'intermediate',
                'sort_order' => 12,
                'is_active' => true,
                'is_premium' => true,
                'plan_tier' => 'professional',
                'supported_colors' => ['indigo', 'emerald', 'rose', 'slate', 'amber', 'violet'],
                'features' => ['Elegant', 'Sophisticated', 'Refined', 'Premium'],
            ],
            [
                'template_id' => 'vertical',
                'name' => 'Vertical Accent',
                'category' => 'Modern & Clean',
                'description' => 'Modern template with a distinctive vertical accent line.',
                'best_for' => 'All Industries, Modern Professionals',
                'complexity_level' => 'beginner',
                'sort_order' => 13,
                'is_active' => true,
                'is_premium' => false,
                'plan_tier' => 'professional',
                'supported_colors' => ['indigo', 'emerald', 'rose', 'slate', 'amber', 'violet'],
                'features' => ['Vertical Accent', 'Modern', 'Clean', 'Simple'],
            ],

            // Structured & Organized
            [
                'template_id' => 'timeline',
                'name' => 'Timeline',
                'category' => 'Chronological Focus',
                'description' => 'Timeline-based layout perfect for showcasing career progression.',
                'best_for' => 'Career Changers, Experienced Professionals',
                'complexity_level' => 'intermediate',
                'sort_order' => 14,
                'is_active' => true,
                'is_premium' => false,
                'plan_tier' => 'professional',
                'supported_colors' => ['indigo', 'emerald', 'rose', 'slate', 'amber', 'violet'],
                'features' => ['Timeline Layout', 'Chronological', 'Career Focus', 'Progressive'],
            ],
            [
                'template_id' => 'split',
                'name' => 'Split Column',
                'category' => 'Organized & Balanced',
                'description' => 'Balanced two-column layout for organized information presentation.',
                'best_for' => 'All Industries, Organized Professionals',
                'complexity_level' => 'intermediate',
                'sort_order' => 15,
                'is_active' => true,
                'is_premium' => false,
                'plan_tier' => 'professional',
                'supported_colors' => ['indigo', 'emerald', 'rose', 'slate', 'amber', 'violet'],
                'features' => ['Two Column', 'Balanced', 'Organized', 'Structured'],
            ],
            [
                'template_id' => 'columnar',
                'name' => 'Three Column',
                'category' => 'Information Dense',
                'description' => 'Three-column layout for maximum information density.',
                'best_for' => 'Experienced Professionals, Academic',
                'complexity_level' => 'advanced',
                'sort_order' => 16,
                'is_active' => true,
                'is_premium' => true,
                'plan_tier' => 'professional',
                'supported_colors' => ['indigo', 'emerald', 'rose', 'slate', 'amber', 'violet'],
                'features' => ['Three Column', 'Information Dense', 'Comprehensive', 'Detailed'],
            ],
            [
                'template_id' => 'boxed',
                'name' => 'Boxed Layout',
                'category' => 'Structured & Clear',
                'description' => 'Boxed sections for clear organization and visual hierarchy.',
                'best_for' => 'All Industries, Clear Communicators',
                'complexity_level' => 'beginner',
                'sort_order' => 17,
                'is_active' => true,
                'is_premium' => false,
                'plan_tier' => 'professional',
                'supported_colors' => ['indigo', 'emerald', 'rose', 'slate', 'amber', 'violet'],
                'features' => ['Boxed Sections', 'Clear Structure', 'Organized', 'Visual Hierarchy'],
            ],

            // Bold & Colorful
            [
                'template_id' => 'bold',
                'name' => 'Bold Impact',
                'category' => 'Strong & Confident',
                'description' => 'Make a bold statement with this impactful design.',
                'best_for' => 'Creatives, Leaders, Confident Professionals',
                'complexity_level' => 'intermediate',
                'sort_order' => 18,
                'is_active' => true,
                'is_premium' => false,
                'plan_tier' => 'professional',
                'supported_colors' => ['indigo', 'emerald', 'rose', 'slate', 'amber', 'violet'],
                'features' => ['Bold Design', 'Impactful', 'Confident', 'Strong'],
            ],
            [
                'template_id' => 'colorblock',
                'name' => 'Color Block',
                'category' => 'Modern & Vibrant',
                'description' => 'Vibrant color blocks for a modern, energetic look.',
                'best_for' => 'Designers, Marketers, Creative Industries',
                'complexity_level' => 'advanced',
                'sort_order' => 19,
                'is_active' => true,
                'is_premium' => true,
                'plan_tier' => 'professional',
                'supported_colors' => ['indigo', 'emerald', 'rose', 'slate', 'amber', 'violet'],
                'features' => ['Color Blocks', 'Vibrant', 'Modern', 'Energetic'],
            ],
            [
                'template_id' => 'striped',
                'name' => 'Striped',
                'category' => 'Dynamic & Engaging',
                'description' => 'Dynamic striped design for an engaging visual experience.',
                'best_for' => 'Creatives, Modern Professionals',
                'complexity_level' => 'intermediate',
                'sort_order' => 20,
                'is_active' => true,
                'is_premium' => false,
                'plan_tier' => 'professional',
                'supported_colors' => ['indigo', 'emerald', 'rose', 'slate', 'amber', 'violet'],
                'features' => ['Striped Design', 'Dynamic', 'Engaging', 'Modern'],
            ],
            [
                'template_id' => 'bordered',
                'name' => 'Bordered',
                'category' => 'Classic & Framed',
                'description' => 'Classic bordered design with a framed appearance.',
                'best_for' => 'Traditional Industries, Formal Roles',
                'complexity_level' => 'beginner',
                'sort_order' => 21,
                'is_active' => true,
                'is_premium' => false,
                'plan_tier' => 'professional',
                'supported_colors' => ['indigo', 'emerald', 'rose', 'slate', 'amber', 'violet'],
                'features' => ['Bordered', 'Framed', 'Classic', 'Traditional'],
            ],
            [
                'template_id' => 'compact',
                'name' => 'Compact',
                'category' => 'Space Efficient',
                'description' => 'Maximize content with this space-efficient compact design.',
                'best_for' => 'Experienced Professionals, Information Rich',
                'complexity_level' => 'intermediate',
                'sort_order' => 22,
                'is_active' => true,
                'is_premium' => false,
                'plan_tier' => 'professional',
                'supported_colors' => ['indigo', 'emerald', 'rose', 'slate', 'amber', 'violet'],
                'features' => ['Compact', 'Space Efficient', 'Information Dense', 'Comprehensive'],
            ],
        ];

        foreach ($templates as $template) {
            \App\Models\ResumeTemplate::updateOrCreate(
                ['template_id' => $template['template_id']],
                $template
            );
        }
    }
}
